language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.16"
before_install:
  cpanm -n Devel::Cover::Report::Coveralls Module::Build
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
